name: Documentation Linting

on:
  push:
    branches:
      - main
    paths:
      - 'personal-portfolio/documentation/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli

      - name: Lint documentation
        run: markdownlint personal-portfolio/documentation/
